### ISSUE TITLE
still crashes after latest update 1.21.1 neoforge

### ISSUE THREAD

**Issue by VaporeonScripts** [MehVahdJukaar/FastPaintings#12]
-- Head --
Thread: Render thread
Stacktrace:
	at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:103) ~[loader-4.0.24.jar%23156!/:4.0] {}
-- Mod loading issue for: fastpaintings --
Details:
	Mod file: /home/natsuyami/.local/share/PrismLauncher/instances/NeoForge Testing/.minecraft/mods/fastpaintings-1.21-1.2.13-neoforge.jar
	Failure message: Fast Paintings (fastpaintings) has failed to load correctly
		java.lang.RuntimeException: Mod constructor has unsupported argument interface net.neoforged.fml.event.IModBusEvent. Allowed optional argument classes: IEventBus, ModContainer, FMLModContainer, Dist
	Mod version: 1.21-1.2.13
	Mod issues URL: https://github.com/MehVahdJukaar/FastPaintings/issues
	Exception message: java.lang.RuntimeException: Mod constructor has unsupported argument interface net.neoforged.fml.event.IModBusEvent. Allowed optional argument classes: IEventBus, ModContainer, FMLModContainer, Dist
Stacktrace:
	at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:103) ~[loader-4.0.24.jar%23156!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.ModLoader.lambda$constructMods$3(ModLoader.java:153) ~[loader-4.0.24.jar%23156!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.ModLoader.lambda$dispatchParallelTask$7(ModLoader.java:231) ~[loader-4.0.24.jar%23156!/:4.0] {}
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934) ~[?:?] {re:mixin}
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911) ~[?:?] {}
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) ~[?:?] {}
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?] {}
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?] {}
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?] {re:mixin,re:computing_frames}
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?] {re:mixin,re:computing_frames}
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?] {re:mixin}

**Comment by VaporeonScripts** [comment]
[06:51:26] [modloading-worker-0/ERROR] [ne.ne.fm.ja.FMLModContainer/LOADING]: Failed to create mod instance. ModID: fastpaintings, class net.mehvahdjukaar.fastpaintings.neoforge.FastPaintingsForge
java.lang.RuntimeException: Mod constructor has unsupported argument interface net.neoforged.fml.event.IModBusEvent. Allowed optional argument classes: ModContainer, Dist, FMLModContainer, IEventBus
	at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:103) ~[loader-4.0.24.jar%23156!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.ModLoader.lambda$constructMods$3(ModLoader.java:153) ~[loader-4.0.24.jar%23156!/:4.0] {}
	at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.ModLoader.lambda$dispatchParallelTask$7(ModLoader.java:231) ~[loader-4.0.24.jar%23156!/:4.0] {}
	at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934) [?:?] {re:mixin}
	at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911) [?:?] {}
	at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) [?:?] {}
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) [?:?] {}
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) [?:?] {}
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) [?:?] {re:mixin,re:computing_frames}
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) [?:?] {re:mixin,re:computing_frames}
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) [?:?] {re:mixin}

**Comment by VaporeonScripts** [comment]
im unable to update my mods because of fast paintings :/
