### ISSUE TITLE
Latest Version of this neoforge mod causes still crash reporting another mod as the reason

### ISSUE THREAD

**Issue by VaporeonScripts** [MehVahdJukaar/FastPaintings#14]
-- Mod loading issue for: foodtxf --
Details:
Mod file: /home/natsuyami/.local/share/PrismLauncher/instances/NeoForge Testing/.minecraft/mods/foodtxf-1.21.1-1.7.4-neoforge.jar
Failure message: Food TXF (foodtxf) has failed to load correctly
java.util.ConcurrentModificationException: null
Mod version: 1.21.1-1.7.4-neoforge
Mod issues URL: https://github.com/jahirxtrap/foodtxf/issues
Exception message: java.util.ConcurrentModificationException
Stacktrace:
at java.base/java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1095) ~[?:?] {}
at java.base/java.util.ArrayList$Itr.next(ArrayList.java:1049) ~[?:?] {}
at TRANSFORMER/[configlibtxf@7.2.3-neoforge](mailto:configlibtxf@7.2.3-neoforge)/com.jahirtrap.configlib.TXFConfig.init(TXFConfig.java:109) ~[configlibtxf-7.2.3-neoforge.jar%231033!/:7.2.3-neoforge] {re:classloading}
at TRANSFORMER/[foodtxf@1.21.1-1.7.4-neoforge](mailto:foodtxf@1.21.1-1.7.4-neoforge)/com.jahirtrap.foodtxf.FoodtxfMod.(FoodtxfMod.java:16) ~[foodtxf-1.21.1-1.7.4-neoforge.jar%23673!/:1.21.1-1.7.4-neoforge] {re:classloading}
at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?] {}
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?] {}
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?] {}
at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:115) ~[loader-4.0.24.jar%23156!/:4.0] {}
at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.ModLoader.lambda$constructMods$3(ModLoader.java:153) ~[loader-4.0.24.jar%23156!/:4.0] {}
at MC-BOOTSTRAP/fml_loader@4.0.24/net.neoforged.fml.ModLoader.lambda$dispatchParallelTask$7(ModLoader.java:231) ~[loader-4.0.24.jar%23156!/:4.0] {}
at java.base/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934) ~[?:?] {re:mixin}
at java.base/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911) ~[?:?] {}
at java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483) ~[?:?] {}
at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?] {}
at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?] {}
at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?] {re:mixin,re:computing_frames}
at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?] {re:mixin,re:computing_frames}
at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?] {re:mixin}
removing ur mod makes the game work, this only happens with ur latest version

**Comment by MehVahdJukaar** [comment]
I need latest.log
